apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP # optional
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  containers:
  - name: nginx-container
    image: nginx